config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "static_pages#top"
  resources :users, only: %i[new create]
  resources :shopping_lists do
    post :add_item, on: :collection
    patch :update_status, on: :member
  end
  
  resources :shopping_list_items, only: [ :update ]
  resources :purchase_histories
  resources :items do
    collection do
      get :autocomplete
    end
  end
  resources :purchase_histories, only: %i[create index]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category

  has_many :shopping_list_items, dependent: :destroy
  has_many :shopping_lists, through: :shopping_list_items

  has_many :purchase_histories, dependent: :destroy
end

app/models/purchase_history.rb
class PurchaseHistory < ApplicationRecord
  belongs_to :user
  belongs_to :item
  belongs_to :shopping_list
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user

  has_many :shopping_list_items, dependent: :destroy
  has_many :items, through: :shopping_list_items
  has_one :purchased_history, dependent: :destroy

  validates :title, presence: true

  enum status: {incomplete: 0, complete: 1 }

  def self.statuses_i18n
    statuses.keys.index_with do |key|
      I18n.t("activerecord.attributes.shopping_list.status.#{key}")
    end
  end

  def status_i18n
    I18n.t("activerecord.attributes.shopping_list.status.#{status}")
  end
end

app/models/shopping_list_item.rb
class ShoppingListItem < ApplicationRecord
  belongs_to :shopping_list
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :shopping_lists, dependent: :destroy
  has_many :purchase_histories, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # サポートされているブラウザのみ機能を使えるようにしている
  allow_browser versions: :modern
  # ログイン済みユーザーのみがアクセス可能
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def autocomplete
    items = Item.where("name ILIKE ?", "%#{params[:q]}%").limit(10)
    render json: items.select(:id, :name)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top]
  def top; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, notice: "登録完了したにょーん^^"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/purchase_histories_helper.rb
module PurchaseHistoriesHelper
end

app/helpers/shopping_list_items_helper.rb
module ShoppingListItemsHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Myapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body>
<% if logged_in? %>
  <%= render "shared/header" %>
<% else %>
  <%= render "shared/before_login_header" %>
<% end %>

<% if flash[:notice] %>
<% binding.pry%>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

  <main class="flex-1 py-12 bg-blue-50">
    <%= yield %>
  </main>

  <%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_before_login_header.html.erb
<nav class="relative bg-white shadow dark:bg-gray-800">
  <div class="container px-6 py-4 mx-auto flex justify-between items-center">
    
    <!-- ロゴ部分 -->
    <div class="flex items-center">
      <%= link_to root_path do %>
        <%= inline_svg_tag "heroicons-outline/shopping-cart-icon-header.svg", class: "w-6 h-6 text-white", alt: "Logo" %>
      <% end %>
    </div>

    <!-- トップリンク + ハンバーガーを横並びに -->
    <div class="flex items-center space-x-4" data-controller="hamburger">
      
      <!-- トップリンク -->
      <%= link_to "新規登録", '#', class: "bg-white border-4 border-blue-400 rounded-lg text-blue px-4 py-2 hover:bg-blue-700" %>
      <%= link_to "ログインはこちら", '#', class: "bg-white border-4 border-blue-400 rounded-lg text-blue px-4 py-2 hover:bg-blue-700" %>
      <!-- ハンバーガーメニュー開ボタン -->
      <button
        data-action="click->hamburger#open"
        data-hamburger-target="button"
        class="bg-blue-600 p-2 rounded-lg text-white hover:bg-blue-700"
      >
        <%= inline_svg_tag "heroicons-outline/hamburger_icon.svg", class: "w-6 h-6", alt: "メニュー" %>
      </button>


  <!-- ハンバーガーメニュー（初期は非表示） -->
  <div
    data-hamburger-target="results"
    class="hidden flex flex-col items-start px-6 space-y-4 mt-4"
  >
    <!-- 閉じるボタン -->
    <button
      data-action="click->hamburger#close"
      data-hamburger-target="button"
      class="bg-blue-600 rounded-lg text-white px-4 py-2 hover:bg-blue-700"
    >
      閉じる
    </button>

    <!-- メニュー項目 -->
    <%= link_to "トップ", '#', class: "text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400" %>
    <%= link_to "買い物リスト一覧", shopping_lists_path, class: "text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400" %>
    <%= link_to "買い物リスト作成", new_shopping_list_path, class: "text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400" %>
  </div>
  </div>
   </div>
</nav>

app/views/shared/_header.html.erb
<nav class="relative bg-white shadow dark:bg-gray-800">
  <div class="container px-6 py-4 mx-auto flex justify-between items-center">
    <div class="flex items-center">
      <%= link_to root_path do %>
        <%= inline_svg_tag "heroicons-outline/shopping-cart-icon-header.svg", class: "w-6 h-6 text-white", alt: "Logo" %>
      <% end %>
    </div>

    <div data-controller = "hamburger">

      <button data-action="click->hamburger#open" 
              data-hamburger-target = "button"
              class="bg-blue-600 rounded-lg text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400">
    <div>
              <%= inline_svg_tag "heroicons-outline/hamburger_icon.svg", class: "w-6 h-6 text-white", alt: "Logo" %>
    </div>
  </button>

    <div data-hamburger-target = "results" class="hidden flex flex-col space-y-4 mt-12">
      <button data-action="click->hamburger#close" 
              data-hamburger-target = "button" 
              class="bg-blue-600 rounded-lg text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400">
    閉じる
  </button>
      <%= link_to "トップ", '#', class: "text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400" %>
      <%= link_to "買い物リスト一覧", shopping_lists_path, class: "text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400" %>
      <%= link_to "買い物リスト作成", new_shopping_list_path, class: "text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400" %>

      <%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete }, class: "px-4 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-500 transition" %>
    </div>
    </div>
  </div>
  </div>
</nav>