config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "static_pages#top"
  resources :users, only: %i[new create]
  resources :shopping_lists do
    post :add_item, on: :collection
    patch :update_status, on: :member
  end
  
  resources :shopping_list_items, only: [ :update ]
  resources :purchase_histories
  resources :items do
    collection do
      get :autocomplete
    end
  end
  resources :purchase_histories, only: %i[create index]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category

  has_many :shopping_list_items, dependent: :destroy
  has_many :shopping_lists, through: :shopping_list_items

  has_many :purchase_histories, dependent: :destroy
end

app/models/purchase_history.rb
class PurchaseHistory < ApplicationRecord
  belongs_to :user
  belongs_to :item
  belongs_to :shopping_list
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user

  has_many :shopping_list_items, dependent: :destroy
  has_many :items, through: :shopping_list_items
  has_one :purchased_history, dependent: :destroy

  validates :title, presence: true

  enum status: {incomplete: 0, complete: 1 }

  def self.statuses_i18n
    statuses.keys.index_with do |key|
      I18n.t("activerecord.attributes.shopping_list.status.#{key}")
    end
  end

  def status_i18n
    I18n.t("activerecord.attributes.shopping_list.status.#{status}")
  end
end

app/models/shopping_list_item.rb
class ShoppingListItem < ApplicationRecord
  belongs_to :shopping_list
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :shopping_lists, dependent: :destroy
  has_many :purchase_histories, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # サポートされているブラウザのみ機能を使えるようにしている
  allow_browser versions: :modern
  # ログイン済みユーザーのみがアクセス可能
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def autocomplete
    items = Item.where("name ILIKE ?", "%#{params[:q]}%").limit(10)
    render json: items.select(:id, :name)
  end
end

app/controllers/purchase_histories_controller.rb
class PurchaseHistoriesController < ApplicationController
  def index
    binding.pry
        @purchase_histories = current_user.purchase_histories.all
  end

  def create
    user_shopping_list = current_user.shopping_lists.find(params[:id])

    ActiveRecord::Base.transaction do
      user_shopping_list.shopping_list_items.each do |item|
        history = current_user.purchase_histories.build(
          item_id: item.item_id,
          purchased_at: Time.current
        )

        unless history.save
          Rails.logger.error("保存失敗💩: #{history.errors.full_messages}")
          flash[:alert] = "保存失敗💩: #{history.errors.full_messages.join(', ')}"
          raise ActiveRecord::Rollback
        end
      end
    end

    redirect_to shopping_lists_path, notice: "購入完了したにょーん💩"
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :require_login
  def index
    @shopping_lists = ShoppingList.includes(:user)
  end

  def new
    @shopping_list = ShoppingList.new
    @shopping_list.shopping_list_items.build
  end

  def create
    @shopping_list = current_user.shopping_lists.build(shopping_list_params)
    shopping_list_items_params = shopping_list_items_raw
    if @shopping_list.save
      # 子要素を手動で保存
      shopping_list_items_params.each do |item_data|
        @shopping_list.shopping_list_items.create(
          item_id: item_data[:item_id],
          quantity: item_data[:quantity]
        )
      end

      redirect_to shopping_list_path(@shopping_list), notice: "作成完了✍️"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @shopping_list = current_user.shopping_lists.find(params[:id])
  end

  def edit
    @shopping_list = current_user.shopping_lists.find(params[:id])
  end
  def update
    @shopping_list = current_user.shopping_lists.find(params[:id])
    if @shopping_list.update(shopping_list_params)
      redirect_to shopping_list_path(@shopping_list)
    else
      render edit, notice: "もう一度オネシャス🙇"
    end
  end

  def destroy
    @shopping_list = current_user.shopping_lists.find(params[:id])
    if @shopping_list.destroy
      render index, notice: "削除したにょーん✌️"
    else
      render index, notice: "失敗したにょん、、、、😭"
    end
  end

  def add_item
    data = shopping_list_items_raw
    # エラー起きてるのでチェック必要
    default_category = Category.find_or_create_by(name: "未分類")
    @item = Item.find_or_create_by(name: data[:item_name]) do |item|
     item.unit = "個" # または他のデフォルト
     item.category = default_category
    end
    @quantity = data[:quantity].to_i
    @recently_purchased = PurchaseHistory.exists?(user: current_user, item: @item)


    respond_to do |format|
      format.turbo_stream
    end
  end

  def update_status
    shopping_list = current_user.shopping_lists.find(params[:id])
    ActiveRecord::Base.transaction do
      shopping_list.update!(status: params[:shopping_list][:status])
  
      if shopping_list.complete?
        shopping_list.create_purchased_history!(purchased_at: Time.current)
      else
        shopping_list.purchased_history&.destroy!
      end
    end
    redirect_to shopping_list_path(shopping_list), notice: "更新しました"
  rescue => e
    redirect_to shopping_list_path(shopping_list), alert: "更新に失敗しました: #{e.message}"
  end
  
  
  private

  def shopping_list_params
    params.require(:shopping_list).permit(:title)
  end

  # 子モデル用（permitしない。ハッシュのままで処理）
  def shopping_list_items_raw
    params[:shopping_list][:shopping_list_items]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top]
  def top; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    binding.pry

    if @user
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, notice: "登録完了したにょーん^^"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/purchase_histories_helper.rb
module PurchaseHistoriesHelper
end

app/helpers/shopping_list_items_helper.rb
module ShoppingListItemsHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_autocomplete.html.erb
<% @items.each do |item| %>
  <li data-id="<%= item.id %>" data-text="<%= item.name %>">
    <%= item.name %>
  </li>
<% end %>

app/views/purchase_histories/_purchase_history.html.erb
<div class="p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
        <h3 class="text-xl font-Retro text-gray-800 dark:text-white mb-2">📦 <%= purchase_history.title %></h3>
        <% binding.pry%>

        <p class="text-sm text-gray-500 dark:text-gray-400 mb-1">👤 <%= shopping_list.user.name %></p>
        <p class="text-sm text-gray-500 dark:text-gray-400 mb-2">📅 <%= l(shopping_list.created_at, format: :short) %></p>

        <p class="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">🛒 商品内容:</p>
        <ul class="pl-4 mb-4 list-disc text-gray-600 dark:text-gray-400 text-sm">
          <% shopping_list.shopping_list_items.each do |sli| %>
            <li><%= sli.item.name %>（<%= sli.quantity %><%= sli.item.unit %>）</li>
          <% end %>
        </ul>

        <div class="flex justify-end gap-3">
          <%= link_to "詳細", shopping_list_path(shopping_list) , class: "text-blue-600 hover:underline text-sm" %>
          <%= link_to "編集", shopping_list_path(shopping_list),class: "text-yellow-600 hover:underline text-sm" %>
          <%= link_to "削除", shopping_list_path(shopping_list),  method: :delete,data: { turbo: false, confirm: "削除しますか？" }, class: "text-red-600 hover:underline text-sm" %>
        </div>
      </div>

app/views/purchase_histories/index.html.erb
<section class="container px-4 mx-auto pt-10 pb-[120px]">
  <div class="bg-white border-l-4 border-blue-500 shadow p-4 mb-6 rounded dark:bg-gray-800 dark:border-blue-400">
  <h2 class="text-xl font-zenKurenaido text-gray-800 dark:text-white">
    📝 買い物リスト一覧
  </h2>
  </div>


  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
    <%# _shopping_list.html.erbでループ表示 %>
   <%= render @purchase_histories %>
  </div>
</section>

app/views/shopping_lists/_added_item.html.erb
<%= turbo_stream.append "added-items" do %>
  <div class="p-2 border rounded">
    <p><strong><%= @item.name %></strong> - 数量: <%= @quantity %></p>
    <% if @recently_purchased %>
      <div class="text-sm text-red-600">⚠️ 最近購入済み</div>
    <% end %>

    <%= hidden_field_tag "shopping_list[shopping_list_items][][item_id]", @item.id %>
    <%= hidden_field_tag "shopping_list[shopping_list_items][][quantity]", @quantity %>
  </div>
<% end %>

app/views/shopping_lists/_shopping_list.html.erb
<div class="p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
        <h3 class="text-xl font-Retro text-gray-800 dark:text-white mb-2">📦 <%= shopping_list.title %></h3>

        <p class="text-sm text-gray-500 dark:text-gray-400 mb-1">👤 <%= shopping_list.user.name %></p>
        <p class="text-sm text-gray-500 dark:text-gray-400 mb-2">📅 <%= l(shopping_list.created_at, format: :short) %></p>

        <p class="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">🛒 商品内容:</p>
        <ul class="pl-4 mb-4 list-disc text-gray-600 dark:text-gray-400 text-sm">
          <% shopping_list.shopping_list_items.each do |sli| %>
            <li><%= sli.item.name %>（<%= sli.quantity %><%= sli.item.unit %>）</li>
          <% end %>
        </ul>
        <%= form_with model: shopping_list, url: update_status_shopping_list_path(shopping_list), method: :patch, local: true do |f| %>
  <%= f.select :status, ShoppingList.statuses_i18n.invert.to_a %>
  <%= f.submit "更新" %>
<% end %>


        <div class="flex justify-end gap-3">
          <%= link_to "詳細", shopping_list_path(shopping_list) , class: "text-blue-600 hover:underline text-sm" %>
          <%= link_to "編集", shopping_list_path(shopping_list),class: "text-yellow-600 hover:underline text-sm" %>
          <%= link_to "削除", shopping_list_path(shopping_list),  method: :delete,data: { turbo: false, confirm: "削除しますか？" }, class: "text-red-600 hover:underline text-sm" %>
        </div>
      </div>

app/views/shopping_lists/add_item.turbo_stream.erb
<%= turbo_stream.append "added-items", partial: "shopping_lists/added_item", locals: { item: @item, quantity: @quantity, warning: @recently_purchased } %>

app/views/shopping_lists/edit.html.erb
<div class="flex items-center justify-between flex-col pt-20 pb-[120px]">
  <div class="max-w-2xl px-8 py-4 bg-white rounded-lg shadow-md dark:bg-gray-800">

    <h2 class="text-xl font-bold text-gray-700 dark:text-white mb-4">
      📝 買い物リストを編集
    </h2>

    <%= form_with model: @shopping_list, local: true do |f| %>
      <div class="mb-4">
        <%= f.label :title, "タイトル", class: "block text-gray-700 dark:text-gray-200 mb-1" %>
        <%= f.text_field :title, class: "w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring focus:ring-blue-300 dark:bg-gray-700 dark:text-white dark:border-gray-600" %>
      </div>

      <div class="mb-4">
        <h3 class="text-lg font-semibold text-gray-700 dark:text-white mb-2">🛒 商品リスト</h3>
        <%= f.fields_for :shopping_list_items do |item_fields| %>
          <div class="mb-2">
            <%= item_fields.label :item_id, "商品", class: "block text-sm text-gray-600 dark:text-gray-300" %>
            <%= item_fields.collection_select :item_id, Item.all, :id, :name, { prompt: "選択してください" }, class: "w-full px-3 py-2 border rounded-lg mb-2 dark:bg-gray-700 dark:text-white dark:border-gray-600" %>

            <%= item_fields.label :quantity, "数量", class: "block text-sm text-gray-600 dark:text-gray-300" %>
            <%= item_fields.number_field :quantity, class: "w-24 px-3 py-2 border rounded-lg dark:bg-gray-700 dark:text-white dark:border-gray-600" %>
            <%= link_to '商品を削除', '#', class: "text-black bg-blue-500 rounded-lg"%>
          </div>
        <% end %>
      </div>

      <div class="flex items-center mt-10 gap-4">
        <%= f.submit '更新する', class: "px-6 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-600 rounded-lg hover:bg-blue-500 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-80" %>

        <%= link_to 'キャンセル', shopping_lists_path,
            class: "px-6 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-gray-600 rounded-lg hover:bg-gray-500 focus:outline-none focus:ring focus:ring-gray-300 focus:ring-opacity-80" %>
      </div>
    <% end %>

  </div>
</div>

app/views/shopping_lists/index.html.erb
<section class="container px-4 mx-auto pt-10 pb-[120px]">
  <div class="bg-white border-l-4 border-blue-500 shadow p-4 mb-6 rounded dark:bg-gray-800 dark:border-blue-400">
  <h2 class="text-xl font-zenKurenaido text-gray-800 dark:text-white">
    📝 買い物リスト一覧
  </h2>
  </div>


  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
    <%# _shopping_list.html.erbでループ表示 %>
   <%= render @shopping_lists %>
  </div>
</section>

app/views/shopping_lists/new.html.erb
<div class="max-w-3xl mx-auto overflow-hidden bg-white rounded-lg shadow-md ">
  <% if flash[:notice] %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

  <%# カート追加 %>
<%= form_with model: @shopping_list, url: add_item_shopping_lists_path, method: :post, data: { turbo_stream: true }, local: false do |f| %>

  <%= f.fields_for :shopping_list_items do |item_fields| %>
  <div class="mb-4 p-4 border rounded">
    <div data-controller="item-autocomplete">
      <%= item_fields.label :item_id, "商品名" %>
      <input type="text"
       data-item-autocomplete-target="input"
       data-action="input->item-autocomplete#search"
       placeholder="商品名を入力"
       name="shopping_list[shopping_list_items][item_name]"
       class="border rounded p-1 w-full" />

      <%= item_fields.hidden_field :item_id, data: { item_autocomplete_target: "hidden" } %>

      <ul data-item-autocomplete-target="results"
          class="border bg-white absolute z-50 mt-1 rounded shadow w-full"></ul>
    </div>

    <div>
      <%= item_fields.label :quantity, "数量" %>
      <%= item_fields.number_field :quantity, class: "border rounded p-1 w-20" %>
    </div>
  </div>
<% end %>

  <div class="mt-4">
    <%= f.submit "カートに追加", class: "bg-blue-600 text-white px-4 py-2 rounded" %>
  </div>
<% end %>
<%# DB保存 %>
  <%= form_with model: @shopping_list, method: :post do |f| %>
  <div class="mb-4">
    <%= f.label :title, "買い物リストのタイトル" %>
    <%= f.text_field :title, class: "border rounded p-2 w-full" %>
  </div>

  <%# turbo_streamで指定する要素 %>
  <div id="added-items"></div> 

  <%= f.submit "リスト作成", class: "bg-blue-600 text-white px-4 py-2 rounded" %>
<% end %>

</div>

app/views/shopping_lists/show.html.erb
<div class="flex items-center justify-between flex-col pt-20 pb-[120px]">
  <div class="max-w-2xl px-8 py-4 bg-white rounded-lg shadow-md dark:bg-gray-800">

    <div class="mt-2">
      <h2 class="text-xl font-bold text-gray-700 dark:text-white hover:text-gray-600 dark:hover:text-gray-200 hover:underline" tabindex="0" role="link">
        <%= @shopping_list.title %>
      </h2>

      <% if @shopping_list.shopping_list_items.any? %>
        <ul class="mt-2 list-disc list-inside text-gray-600 dark:text-gray-300">
          <%# @shopping_listオブジェクトが存在している場合、shopping_list_itemsをインスタンスメソッドで取り出し、itemに入れ（つまり[0]みたいなインデックスによるループ %>
          <% @shopping_list.shopping_list_items.each do |item| %>
            <li class="flex items-center gap-2" id="shopping_list_item_<%= item.id %>">
              <%# 各itemに対して、チェックボックス入力画面を表示 パーシャル化後々%>
              <%= form_with model: item, data: { turbo_frame: "shopping_list_item_#{item.id}" }, class: "inline" do |f| %>
                <%= f.check_box :checked, {
                      checked: item.checked,
                      class: "form-checkbox text-blue-600",
                      onchange: "this.form.requestSubmit()"
                    } %>
              <% end %>
              <span><%= item.item.name %>（数量: <%= item.quantity %>）</span>
            </li>
          <% end %>
      
          <%= button_to "購入完了", purchase_histories_path, { method: :post, params: {id: @shopping_list.id},class: "px-4 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-500 transition" }%>
        </ul>
      <% else %>
        <p class="mt-2 text-gray-500 dark:text-gray-400">
          登録された商品はありません。
        </p>
      <% end %>
    </div>

    <div class="flex items-center mt-10 gap-4">
      <%= link_to '編集', edit_shopping_list_path(@shopping_list),
          class: "px-6 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-600 rounded-lg hover:bg-blue-500 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-80" %>

      <%= link_to '戻る', shopping_lists_path,
          class: "px-6 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-600 rounded-lg hover:bg-blue-500 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-80" %>
    </div>
    
  </div>
</div>

app/views/users/new.html.erb
<section class="max-w-3xl mx-auto px-4 py-12 bg-white dark:bg-gray-800 rounded-lg shadow">
  <h2 class="text-2xl font-bold mb-6 text-center text-gray-800 dark:text-white">新規登録</h2>

  <%= form_with model: @user do |f| %>
    <div class="mb-4">
      <%= f.label :name, "名前", class: "block text-gray-700 dark:text-gray-300 mb-1" %>
      <%= f.text_field :name, class: "w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400" %>
    </div>

    <div class="mb-4">
      <%= f.label :email, "Email", class: "block text-gray-700 dark:text-gray-300 mb-1" %>
      <%= f.email_field :email, class: "w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400" %>
    </div>

    <div class="mb-4">
      <%= f.label :password, "パスワード", class: "block text-gray-700 dark:text-gray-300 mb-1" %>
      <%= f.password_field :password, class: "w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400" %>
    </div>

    <div class="mb-6">
      <%= f.label :password_confirmation, "パスワード確認", class: "block text-gray-700 dark:text-gray-300 mb-1" %>
      <%= f.password_field :password_confirmation, class: "w-full px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400" %>
    </div>

    <div class="text-center">
      <%= f.submit "登録", class: "px-6 py-2 bg-blue-600 text-white rounded hover:bg-blue-500 transition" %>
    </div>
  <% end %>
</section>